### ISSUE TITLE
AFG? 

### ISSUE THREAD

**Issue by markus-lassfolk** [trichner/eve-live-intel#1]
Hi Thomas, 
Are you still playing EVE, and would you be interested in doing more job on this really cool project?

**Comment by trichner** [comment]
Hi, while I still have my subscription I'm not playing that often anymore. Nevertheless I'd still do some coding if there's an interest in the tool.
As far as I remember I stopped working on it because nobody was using it.

**Comment by markus-lassfolk** [comment]
I find the tool very useful and a possible replacement for the alliance intel channel where it's hard to get a good view of things. 
Though, before we can start using it in the alliance, there are a few things that needs to be added. And I guess it might be why this tool has not been widely adopted yet as I would think other alliances faces the same challenges. 
1. Make it easy to just allow "Blue's" to login and use the tool. Alliance only is not enough, need to be everyone with a Blue standing. Would be great if it was possible to use the EVE SSO for that. Like, entering a Corp key for the WebSite, and it will then only allow people who are Blue to see the website. 
2. Make it possible to attach a a copy of "Local Chat" or Link names of the hostiles. Mouseover/click on the system and see the reports for that system 
3. Make it possible to attach a DSCAN of the hostiles. Mouseover/click on the system and see the reports for that system 

Optional: 
1. KillBoard integration. Make systems highlight when there has been a kill in the system, according to zkillboard. Colored based on:  Hostile Death (Blue kill), Friendly Death (Blue death), Neutral Death/Kill (no Blue involved - thirdpary. 
2. Possible to adjust per user, how many jumps out you want to see reports on the map. 

Possible Bug: 
1. I noticed it myself, and had members who first had to trust the site. And it would then popup the request for trusting it.  

I'm more than happy to provide any kind of support you may need. Maybe a dedicated Development server for you if that would help. Or if you want a Friendly and active corp to join  :)

**Comment by trichner** [comment]
1. This would require an API key (also obtainable via SSO).
2. Wouldn't be that hard to add.
3. Same as 2.

The software would also need some refactoring, the `javascript` side of things is kinda buggy.

At the moment I just don't have the time/motivation to extend/fix it.

**Comment by markus-lassfolk** [comment]
I understand, thanks for replying and Marry Xmas :)
